import {parseDXF} from './src/dxf.js';
import {buildPlan} from './src/planner.js';
import {createCampaignMap} from './src/map.js';
import {renderReport,exportReport,buildWhatsAppMessage,downloadText,downloadBlob,coordinateDMM} from './src/reports.js';
import {validateProject} from './src/project.js';
import {logEvent,exportLogs} from './src/logger.js';

const $=id=>document.getElementById(id);
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config,state,plan,map,previewTicket=0,busy=false;
const number=(v,d=0)=>Number(v).toLocaleString('pt-BR',{maximumFractionDigits:d,minimumFractionDigits:d});
function message(text,error=false){const el=$('status-banner');el.hidden=false;el.textContent=text;el.className=error?'status-banner error':'status-banner';logEvent(error?'error':'info',text);}
function meta(){return {date:$('campaign-date').value,blastName:$('campaign-region').value.trim(),time:$('campaign-time').value,operation:$('campaign-operation').value.trim(),responsible:$('campaign-responsible').value.trim(),notes:$('campaign-notes')?.value.trim()||'',crsName:config.crs.find(c=>c.id===state.crs).name,crsZone:24};}
function project(lon,lat){const [x,y]=globalThis.proj4('EPSG:4326',state.crs,[lon,lat]);return {x,y};}
function unproject(x,y){const [lon,lat]=globalThis.proj4(state.crs,'EPSG:4326',[x,y]);return {lon,lat};}
function makePlan(candidate=state){const original=state;state=candidate;try{return buildPlan({polygons:candidate.polygons,communities:candidate.communities.filter(c=>c.enabled),instrumentCount:candidate.instrumentCount,project,unproject,config});}finally{state=original;}}
function collect(){state.meta=meta();state.messageTemplate=$('message-template').value;return {...state,savedAt:new Date().toISOString()};}
function persist(){try{localStorage.setItem(config.storageKey,JSON.stringify(collect()));}catch(e){message(`Campanha calculada, mas não foi possível salvar neste navegador: ${e.message}`,true);}}
function disabledExports(disabled){for(const id of ['export-pdf','export-png','export-txt'])$(id).disabled=disabled;}
function polygonsUI(){
  $('polygon-count').textContent=state.polygons.length;
  $('polygon-list').innerHTML=state.polygons.length?state.polygons.map((p,i)=>`<div class="polygon-item"><div class="polygon-heading"><strong>${escapeHtml(p.name)}</strong><button type="button" class="icon-button" data-remove="${i}" aria-label="Remover ${escapeHtml(p.name)}">×</button></div><small>${p.vertices.length} vértices · ${escapeHtml(p.source||p.layer||'Área importada')}</small><label>Direção de saída (azimute)<div class="direction-field"><input type="number" min="0" max="359.9" step="0.1" placeholder="Não informado" value="${p.direction??''}" data-direction="${i}" aria-label="Direção de ${escapeHtml(p.name)}"><span>°</span></div></label></div>`).join(''):'<div class="empty-state">Importe as poligonais fechadas das áreas de desmonte.</div>';
}
function communitiesUI(){
  $('community-list').innerHTML=state.communities.map((c,i)=>`<details class="community-item"><summary><input type="checkbox" ${c.enabled?'checked':''} data-enabled="${i}" aria-label="Disponibilidade de ${escapeHtml(c.name)}"><span>${escapeHtml(c.name)}</span><small>${c.id}</small></summary><div class="community-fields"><label>Latitude (graus decimais)<input type="number" step="any" value="${c.lat}" data-lat="${i}"></label><label>Longitude (graus decimais)<input type="number" step="any" value="${c.lon}" data-lon="${i}"></label><small>${coordinateDMM(c.lat,'lat')} · ${coordinateDMM(c.lon,'lon')}</small></div></details>`).join('');
}
function syncForm(){const m=state.meta;for(const [id,key] of [['campaign-date','date'],['campaign-region','blastName'],['campaign-time','time'],['campaign-operation','operation'],['campaign-responsible','responsible'],['campaign-notes','notes']])if($(id))$(id).value=m[key];$('instrument-count').value=state.instrumentCount;$('crs-select').value=state.crs;$('message-template').value=state.messageTemplate;polygonsUI();communitiesUI();}
function scenarioUI(){
  $('scenario-cards').innerHTML=plan.scenarios.map(s=>`<button type="button" class="scenario-card ${s.id===state.selectedScenario?'selected active':''}" data-scenario="${s.id}" aria-pressed="${s.id===state.selectedScenario}"><span class="scenario-number">Cenário ${s.id}</span><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.description)}</p><ul>${s.points.map(p=>`<li><span>${escapeHtml(p.name.replace('Comunidade de ',''))}</span><strong>${number(p.distance)} m</strong></li>`).join('')}</ul><small>${s.coincidentWith.length?`Mesmos pontos do cenário ${s.coincidentWith.join(' e ')}.`:'Combinação definida pelo critério.'}</small></button>`).join('');
}
function mapUpdate(){const points=plan?plan.communities:state.communities.filter(c=>c.enabled);map.update({polygons:plan?plan.polygons.map(p=>({...p,coordinates:p.vertices.map(v=>{const c=unproject(v.x,v.y);return[c.lon,c.lat];})})):[],communities:points,origin:plan?.origin,radius:plan?.origin.radius,selectedIds:plan?.scenarios.find(s=>s.id===state.selectedScenario)?.points.map(p=>p.id)||[]});}
function clearResults(){plan=null;previewTicket++;disabledExports(true);$('scenario-cards').innerHTML='<div class="empty-state">Importe as áreas e calcule para comparar os três cenários.</div>';$('report-preview').innerHTML='<div class="empty-state">O relatório será preparado após o cálculo da campanha.</div>';$('origin-coordinates').textContent='Aguardando poligonais';$('radius-value').textContent='—';$('selected-count').textContent='0';mapUpdate();}
async function reportData(){if(!plan)throw Error('Calcule a campanha antes de exportar.');const scenario=plan.scenarios.find(s=>s.id===state.selectedScenario);const mapCanvas=await map.exportCanvas({width:1400,height:1000});return {config,meta:meta(),plan:{...plan,polygons:plan.polygons.map(p=>({...p,azimuth:p.direction,points:p.vertices}))},scenario,mapCanvas:mapCanvas.canvas||mapCanvas,mapCaption:mapCanvas.caption};}
async function preview(){const ticket=++previewTicket;try{const data=await reportData();if(ticket!==previewTicket)return;const canvas=await renderReport(data);if(ticket!==previewTicket)return;canvas.setAttribute('aria-label',`Prévia do relatório do cenário ${state.selectedScenario}`);canvas.className='report-canvas';$('report-preview').replaceChildren(canvas);if($('message-preview'))$('message-preview').textContent=buildWhatsAppMessage(data,$('message-template').value);}catch(e){if(ticket===previewTicket){$('report-preview').textContent=e.message;message(e.message,true);}}}
async function calculate({fit=false}={}){try{if(!$('campaign-form').reportValidity())return;state.instrumentCount=Number($('instrument-count').value);const next=makePlan();plan=next;scenarioUI();mapUpdate();if(fit)map.fit();$('origin-coordinates').textContent=`${coordinateDMM(plan.origin.lat,'lat')} · ${coordinateDMM(plan.origin.lon,'lon')} | E ${number(plan.origin.x,2)} · N ${number(plan.origin.y,2)} m`;$('radius-value').textContent=`${number(plan.origin.radius,1)} m`;$('selected-count').textContent=state.instrumentCount;disabledExports(false);message(`${state.polygons.length} área(s) · ${state.instrumentCount} sismógrafo(s). ${plan.warnings.join(' ')}`);persist();await preview();}catch(e){clearResults();message(e.message,true);}}
function changed(){if(plan)calculate();else persist();}
async function importDXF(files){if(!files.length)return;try{const imported=[],warnings=[];for(const file of files){if(!/\.dxf$/i.test(file.name))throw Error('Selecione somente arquivos DXF.');if(file.size>config.validation.maxFileBytes)throw Error(`${file.name}: arquivo acima do limite de ${config.validation.maxFileBytes/1e6} MB.`);const result=parseDXF(await file.text(),config.validation);warnings.push(...result.warnings);for(const p of result.polygons)imported.push({...p,id:crypto.randomUUID(),name:`${file.name.replace(/\.dxf$/i,'')} · ${p.name}`.slice(0,config.validation.maxLabelLength),source:file.name});}const next={...state,polygons:[...state.polygons,...imported]};makePlan(next);state=next;polygonsUI();await calculate({fit:true});if(warnings.length)message([...(plan?.warnings||[]),...warnings].join(' '));logEvent('import','DXF importado',{files:files.map(f=>f.name),polygons:imported.length});}catch(e){message(`Importação recusada. ${e.message}`,true);}finally{$('dxf-files').value='';}}
async function exportSelected(format){if(busy)return;busy=true;disabledExports(true);try{const data=await reportData();if(format==='txt'){const text=buildWhatsAppMessage(data,$('message-template').value);downloadText(text,`${data.meta.date.replaceAll('-','')}-GMD-cenario-${state.selectedScenario}.txt`);}else await exportReport(data,format);logEvent('export',`Arquivo ${format.toUpperCase()} gerado`,{scenario:state.selectedScenario});message(`Arquivo ${format.toUpperCase()} gerado para o cenário ${state.selectedScenario}.`);}catch(e){message(e.message,true);}finally{busy=false;disabledExports(!plan);}}
function events(){
  $('campaign-form').addEventListener('submit',e=>{e.preventDefault();calculate({fit:true});});
  $('calculate-button').addEventListener('click',e=>{e.preventDefault();calculate({fit:true});});
  $('dxf-files').addEventListener('change',e=>importDXF([...e.target.files]));
  $('polygon-list').addEventListener('click',e=>{const button=e.target.closest('[data-remove]');if(!button)return;state.polygons.splice(Number(button.dataset.remove),1);polygonsUI();state.polygons.length?calculate({fit:true}):(clearResults(),persist());});
  $('polygon-list').addEventListener('change',e=>{if(e.target.dataset.direction===undefined)return;const i=Number(e.target.dataset.direction),v=e.target.value;state.polygons[i].direction=v===''?null:Number(v);calculate();});
  $('community-list').addEventListener('change',e=>{const d=e.target.dataset;for(const field of ['enabled','lat','lon'])if(d[field]!==undefined){const community=state.communities[Number(d[field])];const old=community[field];community[field]=field==='enabled'?e.target.checked:(e.target.value===''?NaN:Number(e.target.value));try{if(state.polygons.length)makePlan();else if(!Number.isFinite(community.lat)||!Number.isFinite(community.lon))throw Error('Coordenada inválida.');}catch(err){community[field]=old;communitiesUI();message(err.message,true);return;}changed();}});
  $('instrument-count').addEventListener('change',()=>{state.instrumentCount=Number($('instrument-count').value);changed();});
  $('crs-select').addEventListener('change',()=>{const old=state.crs;state.crs=$('crs-select').value;try{if(state.polygons.length)makePlan();changed();}catch(e){state.crs=old;$('crs-select').value=old;message(e.message,true);}});
  for(const id of ['campaign-date','campaign-region','campaign-time','campaign-operation','campaign-responsible','campaign-notes'])$(id)?.addEventListener('change',()=>{persist();if(plan)preview();});
  $('scenario-cards').addEventListener('click',e=>{const card=e.target.closest('[data-scenario]');if(!card)return;state.selectedScenario=Number(card.dataset.scenario);scenarioUI();mapUpdate();persist();preview();});
  $('fit-map').addEventListener('click',()=>map.fit());$('map-mode').addEventListener('change',()=>{map.setBasemap($('map-mode').value);if(plan)preview();});
  for(const format of ['pdf','png','txt'])$(`export-${format}`).addEventListener('click',()=>exportSelected(format));
  $('message-template').addEventListener('change',()=>{persist();if(plan)preview();});
  $('save-project').addEventListener('click',()=>{try{const value=validateProject(collect(),config);downloadBlob(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),`campanha-${value.meta.date}.json`);}catch(e){message(e.message,true);}});
  $('load-project').addEventListener('click',()=>$('project-file').click());$('project-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>config.validation.maxFileBytes)throw Error('Projeto acima do limite de tamanho.');const value=validateProject(JSON.parse(await file.text()),config);if(value.polygons.length)makePlan(value);state=value;syncForm();state.polygons.length?await calculate({fit:true}):clearResults();message('Projeto importado e validado.');}catch(err){message(`Projeto recusado. ${err.message}`,true);}finally{e.target.value='';}});
  $('download-log').addEventListener('click',exportLogs);
  $('clear-button').addEventListener('click',()=>{state.polygons=[];if(($('campaign-notes').value||'').startsWith('DEMONSTRAÇÃO:'))$('campaign-notes').value='';state.meta.notes='';polygonsUI();clearResults();persist();message('Áreas removidas. Importe as poligonais da próxima campanha.');});
  $('load-example')?.addEventListener('click',()=>{state.polygons=config.example.offsets.map((vertices,i)=>({id:`demo-${i}`,name:`EXEMPLO — Área ${i+1}`,source:'Geometria demonstrativa; não usar como plano real',vertices:vertices.map(([x,y])=>({x:x+config.example.origin.x,y:y+config.example.origin.y})),direction:config.example.directions[i]}));$('campaign-notes').value='DEMONSTRAÇÃO: áreas fictícias para conhecer a ferramenta. Importe as poligonais reais antes de planejar uma campanha.';polygonsUI();calculate({fit:true});});
}
async function init(){try{const manifest=await fetch('data/manifest.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('Manifesto indisponível.');return r.json();});config=await fetch(manifest.configPath,{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('Configuração indisponível.');return r.json();});for(const c of config.crs)globalThis.proj4.defs(c.id,c.definition);state={schemaVersion:1,crs:config.defaults.crs,polygons:[],communities:structuredClone(config.communities),instrumentCount:config.defaults.instrumentCount,selectedScenario:1,messageTemplate:config.report.whatsappTemplate,meta:{date:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Fortaleza'}).format(new Date()),blastName:config.defaults.region,time:'',operation:config.defaults.operation,responsible:config.defaults.responsible,notes:''}};try{const saved=localStorage.getItem(config.storageKey);if(saved){const candidate=validateProject(JSON.parse(saved),config);if(candidate.polygons.length)makePlan(candidate);state=candidate;}}catch(e){message(`Campanha salva não restaurada: ${e.message}`,true);}$('crs-select').innerHTML=config.crs.map(c=>`<option value="${c.id}">${escapeHtml(c.name)} (${c.id})</option>`).join('');$('campaign-notes').maxLength=config.validation.maxNotesLength;map=createCampaignMap('map',config);syncForm();events();logEvent('init','Planejador inicializado',{version:config.version});state.polygons.length?await calculate({fit:true}):clearResults();}catch(e){message(`Falha ao iniciar: ${e.message}`,true);}finally{$('loading-overlay').hidden=true;}}
init();
